### ISSUE TITLE
`regeneratorRuntime is not defined`

### ISSUE THREAD

**Issue by irisjae** [NadavShaar/react-grid-table#64]
Hi @NadavShaar, thanks a lot for publishing this polished table component.

However, it seems that the dist code of your component relies on a deprecated babel polyfill to be globally available.

When I tried copying your demo at https://codesandbox.io/s/react-grid-table-demo-3275n?file=/src/App.js into my project, I received the error `Uncaught ReferenceError: regeneratorRuntime is not defined` which appears to be caused by a global babel dependency.

See this [link](https://stackoverflow.com/a/56754212/15181635) for more information, and I suppose you may attempt the option 2 highlighted, so that the dist library code can run standalone.

Perhaps consider adding the src folder to the npm package as well, so that I may directly import your component source, using my own babel version.

**Comment by NadavShaar** [comment]
Hello irisjae..
Thanks reporting about this issue I'll check it out.

Have a great day!

**Comment by irisjae** [comment]
Hi @NadavShaar, I've made a [minimal test case](https://github.com/irisjae/react-grid-table-example-case.git ) to show you what I mean.

The test case repo is a completely barebones React app with exactly one component, built with webpack. Run `build-normal-component.sh` to build the setup with some random React component. You may serve the `normal-component.html` with something like `npx serve` and verify that it works. Run `build-broken-component.sh` to build the same setup for `react-grid-table`, and you can reproduce this error at `broken-component.html`. The error appears to be that the library dist is not completely self contained, maybe some mistake during bundling setup?

Thanks a lot!
Cheers.

**Comment by NadavShaar** [comment]
Hi irisjae...
I'm not familiar with this kind of application setup can you please try testing it in a basic [create-react-app](https://github.com/facebook/create-react-app) setup?

**Comment by irisjae** [comment]
As you know, create-react-app is a somewhat opinionated and non-trivial build setup; the bug being that this component only works on create-react-app setups and breaks for any other React setups (which it shouldn't), this bug is probably due to the project only being tested on create-react-app setups.

I've quickly created a really small pull request which fixes the issue, see if it works for you to work. If you would really still like it, then I can perhaps get a minimal project from CRA which demonstrates the issue (really, the previous application setup which I linked you to is super super minimal, every file is pretty much a one-liner, you can see that its a bug when the component breaks for that case).

Have a nice day.

**Comment by ilayofir** [comment]
Hi @irisjae .
Looks like the problem comes from @babel/plugin-transform-runtime not being used in your compilation. We will see if this issue can be resolved, as this is a pretty significant disadvantage.
In the meantime, you can try adding it when compiling and see if this resolves your issue.

**Comment by irisjae** [comment]
@ilayofir fyi using the npm version of the package with babel transform plugins don't work given that I don't otherwise trigger a global regeneratorRuntime polyfill, as the babel code has already been compiled.

**Comment by NadavShaar** [comment]
Fixed in version 0.3.0

**Comment by irisjae** [comment]
@NadavShaar I confirm that `regeneratorRuntime is not defined` is still an issue with version `1.0.2`, perhaps should reopen?

**Comment by VrTech** [comment]
Not defined :(
